#!/usr/bin/bash
set -e
CWD="$(cd "$(dirname "$0")" && pwd)"
STATE_DIR="$(cd "$CWD/.." && pwd)"
SECRET_DIR="$(cd "$CWD/.." && pwd)"

main()
{
    STATE="$STATE_DIR/naughtybot-state.json"
    SECRET="$SECRET_DIR/naughtybot-secret.json"

    [[ -e $STATE ]] || echo "{}" > "$STATE"
    [[ -e $SECRET ]] || echo "{}" > "$SECRET"

    requires-bin FORMAT_MAIL "$CWD/format-mail"
    requires-bin JQ "$(which jq)"
    requires-bin FLOCK "$(which flock)"
    requires-bin CURL "$(which curl)"
    requires-bin PANDOC "$(which pandoc)"

    local secrets
    secrets="$(read-secret secret_do-read)"
    {
        read -r SECRET_BOT_TOKEN
        read -r SECRET_BOT_CHAT
        read -r SECRET_MAIL_SERVER
        read -r SECRET_MAIL_PORT
        read -r SECRET_MAIL_USERNAME
        read -r SECRET_MAIL_PASSWORD
        read -r SECRET_MAIL_INSECURE
    } <<< "$secrets"
    SECRET_MAIL_URL="pop3s://$SECRET_MAIL_SERVER:$SECRET_MAIL_PORT"
    SECRET_MAIL_CREDENTIAL="default login $SECRET_MAIL_USERNAME password $SECRET_MAIL_PASSWORD"
    SECRET_MAIL_OPTION="$(<<< "$SECRET_MAIL_INSECURE" json -r 'if . then "-k" else "" end')"

    "cmd_$1"
}

cmd_() { cmd_help; }
cmd_--help() { cmd_help; }
cmd_-h() { cmd_help; }

cmd_help()
{
    printf "Naughtybot - Push notification based on Telegram.\n"
    printf "\n"
    printf "USAGE:\n"
    printf "  %s [help | -h | --help]\n" "$0"
    printf "  %s setup\n" "$0"
    printf "  %s mail-check\n" "$0"
    printf "  %s mail-mark-all-as-read\n" "$0"
    printf "  echo MESSAGE | %s queue\n" "$0"
    printf "  echo MESSAGE | %s send\n" "$0"
    printf "  %s flush\n" "$0"
    printf "  %s auto-flush\n" "$0"
    printf "  %s auto-check\n" "$0"
}

cmd_setup()
{
    requires-bin DIALOG "$(which dialog)"
    local result
    result="$(
        "$DIALOG" \
            --stdout \
            --insecure \
            --backtitle "Naughtybot" \
            --title " Setup Secrets " \
            --mixedform " Editing $SECRET" 0 80 7 \
                "BOT" 1 1 "" 0 0 0 0 0 \
                "Token" 2 3 "$SECRET_BOT_TOKEN" 2 9 48 64 0 \
                "Chat" 2 59 "$SECRET_BOT_CHAT" 2 64 10 20 0 \
                "POP3 SSL Mail" 4 1 "" 0 0 0 0 0 \
                "Host" 5 3 "$SECRET_MAIL_SERVER" 5 8 49 65536 0 \
                "Port" 5 59 "$SECRET_MAIL_PORT" 5 64 10 5 0 \
                "Username" 6 3 "$SECRET_MAIL_USERNAME" 6 12 25 1024 0 \
                "Password" 6 40 "$SECRET_MAIL_PASSWORD" 6 49 25 1024 1 \
                "Insecure (Do not check SSL certs. Useful for self-signed certs.)" 7 3 "$SECRET_MAIL_INSECURE" 7 68 6 5 0
    )" || {
        "$DIALOG" \
            --backtitle "Naughtybot" \
            --title " Setup Secrets " \
            --infobox "Canceled." 4 20
        exit 0
    }
    local script="$(cat << "END"
        split("\n")
        | {
            bot: {
                token: .[0],
                chat: .[1],
            },
            "mail-pop3s": {
                server: .[2],
                port: .[3]
                    | (if . == "" then 995 else . end)
                    | tonumber
                    | (if . < 1 or . > 65535 then error("Port must be in range 1~65535") else . end)
                ,
                username: .[4],
                password: .[5],
                insecure: .[6]
                    | (if . == "" then "false" else . end)
                    | fromjson
                ,
            },
        }
        | if .["mail-pop3s"].port == 995 then del(.["mail-pop3s"].port) else . end
        | if .["mail-pop3s"].insecure then . else del(.["mail-pop3s"].insecure) end
END
    )"
    result="$(<<< "$result" json -Rs "$script")"

    "$DIALOG" \
        --backtitle "Naughtybot" \
        --title " Setup Secrets " \
        --infobox "Updating $SECRET" 8 60

    <<< "$result" update-secret secret_do-update

    "$DIALOG" \
        --backtitle "Naughtybot" \
        --title " Setup Secrets " \
        --infobox "Updated $SECRET" 8 50
}

cmd_mail-mark-all-as-read()
{
    printf "Checking for old mails...\n"

    local list
    list="$(fetch-mail-id-list-as-json)"
    <<< "$list" update-state state_do-update-read-mails
}

cmd_queue()
{
    queue-message
}

# - requires_bin VAR path-to-bin
# Ensures path-to-bin exists and is executable.
# If so, it is equivalent to VAR="path-to-bin".
# Otherwise, show error and abort.
requires-bin()
{
    [[ -z $2 ]] && {
        >&2 printf "Executable \e[1;31mnot found\e[0m: %s\n" "$1"
        exit 1
    }

    [[ ! -x $2 ]] && {
        >&2 printf "File \e[1;31mnot executable\e[0m: %s\n" "$2"
        exit 1
    }

    declare -g "$1"="$2"
}

fetch-mail-id-list-as-json()
{
    local list
    list="$(fetch-mail / -X UIDL)"
    <<< "$list" json -Rs 'split("\n") | map(rtrimstr("\r") | select(length > 0) | split(" ") | { (.[1]): .[0] }) | add'
}

# - echo MESSAGE | queue-message
# Put message into sending queue.
queue-message()
{
    "$PANDOC" -f commonmark -t commonmark | update-state state_do-update-append-message
    printf "Queued message (%d in queue).\n" "$(message-count)"
}

# - count="$(message-count)"
# Get number of messages in the sending queue.
message-count()
{
    read-state state_do-read-message-count
}

secret_do-read()
{
    json -r '(.bot | .token // "", .chat // ""), (.["mail-pop3s"] | .server // "", .port // 995, .username // "", .password // "", .insecure // false)' "$SECRET"
}

secret_do-update()
{
    local result
    result="$(json '.')"
    <<< "$result" cat > "$SECRET"
}

state_do-update-read-mails()
{
    local result
    result="$(json --argfile state "$STATE" 'keys | map({ (.): true }) | add as $read | $state | .mail.read += $read')"
    <<< "$result" cat > "$STATE"
}

state_do-update-append-message()
{
    local result
    result="$(json -Rs --argfile state "$STATE" 'rtrimstr("\n") as $message | $state | .message.pending += [$message]')"
    <<< "$result" cat > "$STATE"
}

state_do-read-message-count()
{
    json '.message.pending | length' "$STATE"
}

# - transaction file mode func
# file: The file to be locked
# mode: -x for updating, -s for reading
# func: A function to be run in the transaction
transaction()
{
    (
        "$FLOCK" "$2" 999
        "$3"
    ) 999>> "$1"
}

# - read-secret func
# Invokes func in a read-only transaction to the secret config.
read-secret()
{
    transaction "$SECRET" -s "$1"
}

# - update-secret func
# Invokes func in a read-write transaction to the secret config.
update-secret()
{
    transaction "$SECRET" -x "$1"
}

# - read-state func
# Invokes func in a read-only transaction to the state config.
read-state()
{
    transaction "$STATE" -s "$1"
}

# - update-state func
# Invokes func in a read-write transaction to the state config.
update-state()
{
    transaction "$STATE" -x "$1"
}

json()
{
    "$JQ" --indent 4 "$@"
}

fetch-mail()
{
    local uri="$1"
    shift
    [[ $uri != /* ]] && uri="/$uri"
    local opts="-sSfL $SECRET_MAIL_OPTION"
    "$CURL" $opts "$SECRET_MAIL_URL$uri" --netrc-file <(cat <<< "$SECRET_MAIL_CREDENTIAL") "$@" || {
        >&2 printf "Failed to \e[1;31mfetch mail\e[0m: %s\n" "$SECRET_MAIL_URL$uri $*"
        exit 1
    }
}

main "$@"

